In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [5]:
a = [1,'w',2]

In [6]:
type(a)

list

In [7]:
b = np.array([])

In [8]:
a = np.random.randint(0,200,(3,3,3))
print(a)

[[[ 52  33  47]
  [152 114  67]
  [175  29 101]]

 [[122 141 165]
  [ 79 146  14]
  [ 83  35 187]]

 [[ 95  27  17]
  [132  78  21]
  [ 68 110  79]]]


In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10,-1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [11]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
a.ndim

3

In [15]:
a.shape

(3, 3, 3)

In [16]:
a.size

27

In [17]:
a.ndim

3

In [18]:
data = np.random.randint(1,10,(5,5))

In [19]:
data

array([[1, 2, 4, 3, 9],
       [5, 4, 7, 4, 1],
       [6, 9, 6, 5, 9],
       [5, 1, 6, 6, 1],
       [7, 3, 1, 9, 5]], dtype=int32)

In [20]:
## argmin,sum,

In [21]:
data.argmax(axis=0)

array([4, 2, 1, 4, 0])

In [22]:
data.mean()

np.float64(4.76)

In [23]:
data.mean(axis = 0)

array([4.8, 3.8, 4.8, 5.4, 5. ])

In [24]:
data.mean(axis=1)

array([3.8, 4.2, 7. , 3.8, 5. ])

In [25]:
data.sum()

np.int64(119)

In [26]:
a = np.array([10,20,30,40])


In [27]:
# NumPy Arithmetic Functions Example (Single Cell)

import numpy as np

# Creating two arrays
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Array A:", a)
print("Array B:", b)

# Addition
print("\nAddition (np.add):")
print(np.add(a, b))

# Subtraction
print("\nSubtraction (np.subtract):")
print(np.subtract(a, b))

# Multiplication
print("\nMultiplication (np.multiply):")
print(np.multiply(a, b))

# Division
print("\nDivision (np.divide):")
print(np.divide(a, b))

# Power
print("\nPower (np.power):")
print(np.power(a, b))

# Modulus
print("\nModulus (np.mod):")
print(np.mod(a, b))

# Floor Division
print("\nFloor Division (np.floor_divide):")
print(np.floor_divide(a, b))

# Absolute Difference
print("\nAbsolute Difference (np.abs):")
print(np.abs(a - b))

Array A: [10 20 30 40]
Array B: [1 2 3 4]

Addition (np.add):
[11 22 33 44]

Subtraction (np.subtract):
[ 9 18 27 36]

Multiplication (np.multiply):
[ 10  40  90 160]

Division (np.divide):
[10. 10. 10. 10.]

Power (np.power):
[     10     400   27000 2560000]

Modulus (np.mod):
[0 0 0 0]

Floor Division (np.floor_divide):
[10 10 10 10]

Absolute Difference (np.abs):
[ 9 18 27 36]


In [28]:
data = np.random.randint(0,100,10)
data

array([36, 45, 14, 70, 53, 17, 52, 57, 79, 14], dtype=int32)

In [29]:
data

array([36, 45, 14, 70, 53, 17, 52, 57, 79, 14], dtype=int32)

In [30]:
np.median(data)

np.float64(48.5)

In [31]:
np.mean(data)

np.float64(43.7)

In [32]:
q1=np.percentile(data,25)
q1

np.float64(21.75)

In [33]:
q2 = np.percentile(data,50)
q2

np.float64(48.5)

In [34]:
q3 = np.percentile(data,75)

In [35]:
rang = q3-q1
rang

np.float64(34.25)

In [36]:
data

array([36, 45, 14, 70, 53, 17, 52, 57, 79, 14], dtype=int32)

In [37]:
data = np.array([10,20,np.nan,40,50,np.nan,70])

In [38]:
data

array([10., 20., nan, 40., 50., nan, 70.])

In [39]:
np.isnan(data)

array([False, False,  True, False, False,  True, False])

In [40]:
np.isnan(data).sum()

np.int64(2)

In [41]:
data[~np.isnan(data)]

array([10., 20., 40., 50., 70.])

In [42]:
np.nan_to_num(data,nan=0)

array([10., 20.,  0., 40., 50.,  0., 70.])

In [43]:
mean_value = np.nanmean(data)

In [44]:
np.where(np.isnan(data),mean_value,data)

array([10., 20., 38., 40., 50., 38., 70.])

In [45]:
median_value = np.median(data)

In [46]:
median_value

np.float64(nan)

In [47]:
import numpy as np

In [49]:
data = np.random.randint(0,10,10)

In [50]:
data

array([5, 0, 2, 9, 9, 7, 6, 2, 0, 2], dtype=int32)

In [57]:
data1=data.reshape(5,2) 

In [58]:
data1.ravel()

array([5, 0, 2, 9, 9, 7, 6, 2, 0, 2], dtype=int32)

In [62]:
np.split(data,2)

[array([5, 0, 2, 9, 9], dtype=int32), array([7, 6, 2, 0, 2], dtype=int32)]

In [65]:
np.array_split(data,6)

[array([5, 0], dtype=int32),
 array([2, 9], dtype=int32),
 array([9, 7], dtype=int32),
 array([6, 2], dtype=int32),
 array([0], dtype=int32),
 array([2], dtype=int32)]

In [71]:
data=np.random.randint(0,10,(16,4))
data

array([[4, 9, 3, 0],
       [4, 5, 4, 6],
       [1, 8, 3, 9],
       [2, 7, 1, 2],
       [9, 4, 9, 3],
       [6, 9, 5, 5],
       [7, 1, 1, 7],
       [6, 0, 8, 5],
       [3, 4, 7, 8],
       [4, 4, 3, 4],
       [7, 7, 5, 5],
       [8, 0, 5, 0],
       [9, 6, 2, 8],
       [2, 9, 4, 2],
       [0, 3, 8, 9],
       [3, 8, 8, 9]], dtype=int32)

In [74]:
np.hsplit(data,4)

[array([[4],
        [4],
        [1],
        [2],
        [9],
        [6],
        [7],
        [6],
        [3],
        [4],
        [7],
        [8],
        [9],
        [2],
        [0],
        [3]], dtype=int32),
 array([[9],
        [5],
        [8],
        [7],
        [4],
        [9],
        [1],
        [0],
        [4],
        [4],
        [7],
        [0],
        [6],
        [9],
        [3],
        [8]], dtype=int32),
 array([[3],
        [4],
        [3],
        [1],
        [9],
        [5],
        [1],
        [8],
        [7],
        [3],
        [5],
        [5],
        [2],
        [4],
        [8],
        [8]], dtype=int32),
 array([[0],
        [6],
        [9],
        [2],
        [3],
        [5],
        [7],
        [5],
        [8],
        [4],
        [5],
        [0],
        [8],
        [2],
        [9],
        [9]], dtype=int32)]

In [75]:
np.hsplit(data,[1,2])

[array([[4],
        [4],
        [1],
        [2],
        [9],
        [6],
        [7],
        [6],
        [3],
        [4],
        [7],
        [8],
        [9],
        [2],
        [0],
        [3]], dtype=int32),
 array([[9],
        [5],
        [8],
        [7],
        [4],
        [9],
        [1],
        [0],
        [4],
        [4],
        [7],
        [0],
        [6],
        [9],
        [3],
        [8]], dtype=int32),
 array([[3, 0],
        [4, 6],
        [3, 9],
        [1, 2],
        [9, 3],
        [5, 5],
        [1, 7],
        [8, 5],
        [7, 8],
        [3, 4],
        [5, 5],
        [5, 0],
        [2, 8],
        [4, 2],
        [8, 9],
        [8, 9]], dtype=int32)]

In [76]:
np.vsplit(data,4)

[array([[4, 9, 3, 0],
        [4, 5, 4, 6],
        [1, 8, 3, 9],
        [2, 7, 1, 2]], dtype=int32),
 array([[9, 4, 9, 3],
        [6, 9, 5, 5],
        [7, 1, 1, 7],
        [6, 0, 8, 5]], dtype=int32),
 array([[3, 4, 7, 8],
        [4, 4, 3, 4],
        [7, 7, 5, 5],
        [8, 0, 5, 0]], dtype=int32),
 array([[9, 6, 2, 8],
        [2, 9, 4, 2],
        [0, 3, 8, 9],
        [3, 8, 8, 9]], dtype=int32)]

In [77]:
np.vsplit(data,[4,5])

[array([[4, 9, 3, 0],
        [4, 5, 4, 6],
        [1, 8, 3, 9],
        [2, 7, 1, 2]], dtype=int32),
 array([[9, 4, 9, 3]], dtype=int32),
 array([[6, 9, 5, 5],
        [7, 1, 1, 7],
        [6, 0, 8, 5],
        [3, 4, 7, 8],
        [4, 4, 3, 4],
        [7, 7, 5, 5],
        [8, 0, 5, 0],
        [9, 6, 2, 8],
        [2, 9, 4, 2],
        [0, 3, 8, 9],
        [3, 8, 8, 9]], dtype=int32)]