In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [5]:
a = [1,'w',2]

In [6]:
type(a)

list

In [7]:
b = np.array([])

In [8]:
a = np.random.randint(0,200,(3,3,3))
print(a)

[[[ 81  69  66]
  [184  37 115]
  [175  79  91]]

 [[ 28 147  19]
  [ 36  12 179]
  [143  69  17]]

 [[119  13 184]
  [101 178 195]
  [ 82   1  62]]]


In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10,-1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [11]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
a.ndim

3

In [15]:
a.shape

(3, 3, 3)

In [16]:
a.size

27

In [17]:
a.ndim

3

In [18]:
data = np.random.randint(1,10,(5,5))

In [19]:
data

array([[9, 5, 3, 8, 5],
       [8, 9, 2, 3, 6],
       [3, 2, 6, 5, 3],
       [4, 5, 8, 6, 3],
       [3, 4, 7, 9, 3]], dtype=int32)

In [20]:
## argmin,sum,

In [21]:
data.argmax(axis=0)

array([0, 1, 3, 4, 1])

In [22]:
data.mean()

np.float64(5.16)

In [23]:
data.mean(axis = 0)

array([5.4, 5. , 5.2, 6.2, 4. ])

In [24]:
data.mean(axis=1)

array([6. , 5.6, 3.8, 5.2, 5.2])

In [25]:
data.sum()

np.int64(129)

In [26]:
a = np.array([10,20,30,40])


In [27]:
# NumPy Arithmetic Functions Example (Single Cell)

import numpy as np

# Creating two arrays
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Array A:", a)
print("Array B:", b)

# Addition
print("\nAddition (np.add):")
print(np.add(a, b))

# Subtraction
print("\nSubtraction (np.subtract):")
print(np.subtract(a, b))

# Multiplication
print("\nMultiplication (np.multiply):")
print(np.multiply(a, b))

# Division
print("\nDivision (np.divide):")
print(np.divide(a, b))

# Power
print("\nPower (np.power):")
print(np.power(a, b))

# Modulus
print("\nModulus (np.mod):")
print(np.mod(a, b))

# Floor Division
print("\nFloor Division (np.floor_divide):")
print(np.floor_divide(a, b))

# Absolute Difference
print("\nAbsolute Difference (np.abs):")
print(np.abs(a - b))

Array A: [10 20 30 40]
Array B: [1 2 3 4]

Addition (np.add):
[11 22 33 44]

Subtraction (np.subtract):
[ 9 18 27 36]

Multiplication (np.multiply):
[ 10  40  90 160]

Division (np.divide):
[10. 10. 10. 10.]

Power (np.power):
[     10     400   27000 2560000]

Modulus (np.mod):
[0 0 0 0]

Floor Division (np.floor_divide):
[10 10 10 10]

Absolute Difference (np.abs):
[ 9 18 27 36]


In [28]:
data = np.random.randint(0,100,10)
data

array([11, 50, 20, 59,  6, 64, 32,  7, 48, 22], dtype=int32)

In [29]:
data

array([11, 50, 20, 59,  6, 64, 32,  7, 48, 22], dtype=int32)

In [30]:
np.median(data)

np.float64(27.0)

In [31]:
np.mean(data)

np.float64(31.9)

In [32]:
q1=np.percentile(data,25)
q1

np.float64(13.25)

In [33]:
q2 = np.percentile(data,50)
q2

np.float64(27.0)

In [34]:
q3 = np.percentile(data,75)

In [35]:
rang = q3-q1
rang

np.float64(36.25)

In [36]:
data

array([11, 50, 20, 59,  6, 64, 32,  7, 48, 22], dtype=int32)

In [37]:
data = np.array([10,20,np.nan,40,50,np.nan,70])

In [38]:
data

array([10., 20., nan, 40., 50., nan, 70.])

In [ ]:
np.isnan(data) 

array([False, False,  True, False, False,  True, False])

In [40]:
np.isnan(data).sum()

np.int64(2)

In [41]:
data[~np.isnan(data)]

array([10., 20., 40., 50., 70.])

In [42]:
np.nan_to_num(data,nan=0)

array([10., 20.,  0., 40., 50.,  0., 70.])

In [43]:
mean_value = np.nanmean(data)

In [44]:
np.where(np.isnan(data),mean_value,data)

array([10., 20., 38., 40., 50., 38., 70.])

In [45]:
median_value = np.median(data)

In [46]:
median_value

np.float64(nan)

In [47]:
import numpy as np

In [48]:
data = np.random.randint(0,10,10)

In [60]:
data

array([[1, 1, 3, 2],
       [7, 6, 7, 3],
       [9, 7, 9, 3],
       [8, 3, 0, 2],
       [7, 3, 2, 8],
       [1, 7, 2, 5],
       [1, 5, 1, 9],
       [5, 9, 8, 6],
       [5, 9, 8, 1],
       [3, 7, 0, 5],
       [3, 2, 7, 7],
       [9, 5, 1, 2],
       [9, 5, 7, 2],
       [6, 4, 4, 0],
       [0, 0, 0, 5],
       [2, 0, 2, 3]], dtype=int32)

In [50]:
data1=data.reshape(5,2) 

In [51]:
data1.ravel()

array([8, 7, 3, 8, 0, 9, 5, 5, 9, 9], dtype=int32)

In [ ]:
np.split(data,3)


[array([7, 7, 2, 3, 7], dtype=int32), array([5, 2, 0, 1, 0], dtype=int32)]

In [69]:
np.array_split(data,6)

[array([7, 7], dtype=int32),
 array([2, 3], dtype=int32),
 array([7, 5], dtype=int32),
 array([2, 0], dtype=int32),
 array([1], dtype=int32),
 array([0], dtype=int32)]

In [71]:
data=np.random.randint(0,10,(16,4))
data

array([[9, 7, 5, 0],
       [8, 8, 0, 9],
       [0, 7, 2, 3],
       [8, 6, 2, 5],
       [8, 9, 3, 9],
       [3, 0, 1, 7],
       [1, 5, 7, 8],
       [6, 6, 5, 0],
       [3, 8, 8, 2],
       [2, 9, 0, 2],
       [4, 7, 0, 7],
       [9, 2, 2, 9],
       [1, 7, 6, 6],
       [5, 6, 6, 2],
       [5, 0, 9, 5],
       [4, 4, 2, 3]], dtype=int32)

In [79]:
np.hsplit(data,4)

[array([[9],
        [8],
        [0],
        [8],
        [8],
        [3],
        [1],
        [6],
        [3],
        [2],
        [4],
        [9],
        [1],
        [5],
        [5],
        [4]], dtype=int32),
 array([[7],
        [8],
        [7],
        [6],
        [9],
        [0],
        [5],
        [6],
        [8],
        [9],
        [7],
        [2],
        [7],
        [6],
        [0],
        [4]], dtype=int32),
 array([[5],
        [0],
        [2],
        [2],
        [3],
        [1],
        [7],
        [5],
        [8],
        [0],
        [0],
        [2],
        [6],
        [6],
        [9],
        [2]], dtype=int32),
 array([[0],
        [9],
        [3],
        [5],
        [9],
        [7],
        [8],
        [0],
        [2],
        [2],
        [7],
        [9],
        [6],
        [2],
        [5],
        [3]], dtype=int32)]

In [80]:
data

array([[9, 7, 5, 0],
       [8, 8, 0, 9],
       [0, 7, 2, 3],
       [8, 6, 2, 5],
       [8, 9, 3, 9],
       [3, 0, 1, 7],
       [1, 5, 7, 8],
       [6, 6, 5, 0],
       [3, 8, 8, 2],
       [2, 9, 0, 2],
       [4, 7, 0, 7],
       [9, 2, 2, 9],
       [1, 7, 6, 6],
       [5, 6, 6, 2],
       [5, 0, 9, 5],
       [4, 4, 2, 3]], dtype=int32)

In [91]:
np.hsplit(data,[2,3])

[array([[9, 7],
        [8, 8],
        [0, 7],
        [8, 6],
        [8, 9],
        [3, 0],
        [1, 5],
        [6, 6],
        [3, 8],
        [2, 9],
        [4, 7],
        [9, 2],
        [1, 7],
        [5, 6],
        [5, 0],
        [4, 4]], dtype=int32),
 array([[5],
        [0],
        [2],
        [2],
        [3],
        [1],
        [7],
        [5],
        [8],
        [0],
        [0],
        [2],
        [6],
        [6],
        [9],
        [2]], dtype=int32),
 array([[0],
        [9],
        [3],
        [5],
        [9],
        [7],
        [8],
        [0],
        [2],
        [2],
        [7],
        [9],
        [6],
        [2],
        [5],
        [3]], dtype=int32)]

In [88]:
data

array([[9, 7, 5, 0],
       [8, 8, 0, 9],
       [0, 7, 2, 3],
       [8, 6, 2, 5],
       [8, 9, 3, 9],
       [3, 0, 1, 7],
       [1, 5, 7, 8],
       [6, 6, 5, 0],
       [3, 8, 8, 2],
       [2, 9, 0, 2],
       [4, 7, 0, 7],
       [9, 2, 2, 9],
       [1, 7, 6, 6],
       [5, 6, 6, 2],
       [5, 0, 9, 5],
       [4, 4, 2, 3]], dtype=int32)

In [57]:
np.vsplit(data,4)

[array([[1, 1, 3, 2],
        [7, 6, 7, 3],
        [9, 7, 9, 3],
        [8, 3, 0, 2]], dtype=int32),
 array([[7, 3, 2, 8],
        [1, 7, 2, 5],
        [1, 5, 1, 9],
        [5, 9, 8, 6]], dtype=int32),
 array([[5, 9, 8, 1],
        [3, 7, 0, 5],
        [3, 2, 7, 7],
        [9, 5, 1, 2]], dtype=int32),
 array([[9, 5, 7, 2],
        [6, 4, 4, 0],
        [0, 0, 0, 5],
        [2, 0, 2, 3]], dtype=int32)]

In [89]:
data

array([[9, 7, 5, 0],
       [8, 8, 0, 9],
       [0, 7, 2, 3],
       [8, 6, 2, 5],
       [8, 9, 3, 9],
       [3, 0, 1, 7],
       [1, 5, 7, 8],
       [6, 6, 5, 0],
       [3, 8, 8, 2],
       [2, 9, 0, 2],
       [4, 7, 0, 7],
       [9, 2, 2, 9],
       [1, 7, 6, 6],
       [5, 6, 6, 2],
       [5, 0, 9, 5],
       [4, 4, 2, 3]], dtype=int32)

In [93]:
np.vsplit(data,[2,3])

[array([[9, 7, 5, 0],
        [8, 8, 0, 9]], dtype=int32),
 array([[0, 7, 2, 3]], dtype=int32),
 array([[8, 6, 2, 5],
        [8, 9, 3, 9],
        [3, 0, 1, 7],
        [1, 5, 7, 8],
        [6, 6, 5, 0],
        [3, 8, 8, 2],
        [2, 9, 0, 2],
        [4, 7, 0, 7],
        [9, 2, 2, 9],
        [1, 7, 6, 6],
        [5, 6, 6, 2],
        [5, 0, 9, 5],
        [4, 4, 2, 3]], dtype=int32)]

In [1]:
import numpy as np
import pandas as pd

In [2]:
arr = np.array([10, 20, 30, 40, 50])
arr.shape 


(5,)

In [3]:
arr.dtype

dtype('int64')

In [4]:
arr.size

5

In [5]:
arr.astype(float)

array([10., 20., 30., 40., 50.])

In [7]:
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
arr = np.array([5, 10, 15, 20, 25, 30])
arr

array([ 5, 10, 15, 20, 25, 30])

In [13]:
arr[0:3]

array([ 5, 10, 15])

In [20]:
arr[-2:]

array([25, 30])

In [23]:
arr[::-1]

array([30, 25, 20, 15, 10,  5])

In [25]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
print(arr[1])

[4 5 6]


In [36]:
arr[:,2]

array([3, 6, 9])

In [37]:
arr[arr == 9] = 99

In [38]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 99]])

In [39]:
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])


In [41]:
total = np.sum(arr)
total

np.int64(450)

In [42]:
np.sum(arr,axis=1)

array([ 60, 150, 240])

In [43]:
np.sum(arr,axis=0)

array([120, 150, 180])

In [ ]:
np.mean(arr,axis=1)

array([20., 50., 80.])

In [ ]:
arr = np.array([12, 45, 67, 23, 89, 10, 5, 100])

In [48]:
a = arr > 50
print(a)

[False False  True False  True False False  True]


In [57]:
a = (arr>20) & (arr<80)
print(np.count_nonzero(arr[a]))

3


In [58]:
a = (arr>30)
print(np.count_nonzero(arr[a]))

4


In [62]:
a = np.where(arr<20,0,arr)


In [63]:
print(a)

[  0  45  67  23  89   0   0 100]


In [64]:
arr = np.array([12, 45, 67, 23, 89, 10, 5, 100])

In [1]:
import numpy as np

In [2]:
marks = np.array([[85, 90, 78],
                  [60, 45, 70],
                  [95, 88, 92],
                  [40, 55, 65]])

In [6]:
marks[np.all(marks>50,axis=1)]

array([[85, 90, 78],
       [95, 88, 92]])

In [10]:
marks[np.any(marks>50,axis=1)]

array([[85, 90, 78],
       [60, 45, 70],
       [95, 88, 92],
       [40, 55, 65]])

In [11]:
np.average(marks,axis=1)

array([84.33333333, 58.33333333, 91.66666667, 53.33333333])

In [17]:
totals=np.sum(marks,axis=1)
topper_index = np.argmax(totals)

In [18]:
totals[topper_index]

np.int64(275)

In [20]:
sales = np.array([[200, 150, 300],
                  [400, 500, 250],
                  [100, 200, 150],
                  [350, 450, 400]])    # rows = stores
                                      # columns = Months
                                      

In [23]:
totals=np.sum(sales,axis=1)
totals

array([ 650, 1150,  450, 1200])

In [28]:
best_index=np.argmax(totals)
print(best_index)

3


In [32]:
tot = np.sum(sales,axis=0)
tot

array([1050, 1300, 1100])

In [34]:
best_tot = np.argmax(tot)
print(best_tot)

1


In [39]:
print(sales[totals>900])

[[400 500 250]
 [350 450 400]]


In [40]:
sales = np.array([[200, 150, 300],
                  [400, 500, 250],
                  [100, 200, 150],
                  [350, 450, 400]])

In [41]:
row_sum = sales.sum(axis=1,keepdims=True)
n_sales = sales/row_sum
print(n_sales)

[[0.30769231 0.23076923 0.46153846]
 [0.34782609 0.43478261 0.2173913 ]
 [0.22222222 0.44444444 0.33333333]
 [0.29166667 0.375      0.33333333]]


In [42]:
arr = np.array([10, 20, 10, 30, 40, 20, 50, 10])

In [44]:
np.unique(arr)

array([10, 20, 30, 40, 50])

In [56]:
unique_elements,counts = np.unique(arr,return_counts=True)
frequency = dict(zip(unique_elements,count))
print(frequency)


{np.int64(10): np.int64(3), np.int64(20): np.int64(2), np.int64(30): np.int64(1), np.int64(40): np.int64(1), np.int64(50): np.int64(1)}


In [59]:
t=np.argmax(counts)
most_fre = unique_elements[t]

In [60]:
most_fre

np.int64(10)

In [1]:
import numpy as np

In [6]:
arr = np.random.randint(0,10,(3,3))

In [7]:
arr

array([[7, 5, 7],
       [2, 1, 6],
       [4, 0, 1]], dtype=int32)

In [5]:
np.astype(arr,float)

array([[0., 2., 8.],
       [3., 1., 7.],
       [9., 6., 3.]])