In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])

In [5]:
print(a)

[1 2 3]


In [6]:
a = [1,'w',2]

In [7]:
type(a)

list

In [8]:
b = np.array([])

In [9]:
a = np.random.randint(0,200,(3,3,3))
print(a)

[[[134  72 104]
  [182  92  83]
  [ 70  86 135]]

 [[104 111 146]
  [116  57  67]
  [  0  22 125]]

 [[ 13 139 177]
  [ 74   1  94]
  [101 121 173]]]


In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(10,-1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [12]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
a.ndim

1

In [16]:
a.shape

(3, 3, 3)

In [17]:
a.size

27

In [18]:
a.ndim

3

In [19]:
data = np.random.randint(1,10,(5,5))

In [30]:
data

array([[2, 4, 8, 7, 7],
       [9, 8, 6, 1, 7],
       [7, 1, 4, 8, 4],
       [5, 5, 6, 7, 4],
       [4, 8, 1, 6, 1]], dtype=int32)

In [21]:
## argmin,sum,

In [22]:
data.argmax(axis=0)

array([1, 1, 0, 2, 0])

In [23]:
data.mean()

np.float64(5.2)

In [24]:
data.mean(axis = 0)

array([5.4, 5.2, 5. , 5.8, 4.6])

In [25]:
data.mean(axis=1)

array([5.6, 6.2, 4.8, 5.4, 4. ])

In [26]:
data.sum()

np.int64(130)

In [27]:
a = np.array([10,20,30,40])


In [28]:
# NumPy Arithmetic Functions Example (Single Cell)

import numpy as np

# Creating two arrays
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Array A:", a)
print("Array B:", b)

# Addition
print("\nAddition (np.add):")
print(np.add(a, b))

# Subtraction
print("\nSubtraction (np.subtract):")
print(np.subtract(a, b))

# Multiplication
print("\nMultiplication (np.multiply):")
print(np.multiply(a, b))

# Division
print("\nDivision (np.divide):")
print(np.divide(a, b))

# Power
print("\nPower (np.power):")
print(np.power(a, b))

# Modulus
print("\nModulus (np.mod):")
print(np.mod(a, b))

# Floor Division
print("\nFloor Division (np.floor_divide):")
print(np.floor_divide(a, b))

# Absolute Difference
print("\nAbsolute Difference (np.abs):")
print(np.abs(a - b))

Array A: [10 20 30 40]
Array B: [1 2 3 4]

Addition (np.add):
[11 22 33 44]

Subtraction (np.subtract):
[ 9 18 27 36]

Multiplication (np.multiply):
[ 10  40  90 160]

Division (np.divide):
[10. 10. 10. 10.]

Power (np.power):
[     10     400   27000 2560000]

Modulus (np.mod):
[0 0 0 0]

Floor Division (np.floor_divide):
[10 10 10 10]

Absolute Difference (np.abs):
[ 9 18 27 36]


In [32]:
data = np.random.randint(0,100,10)
data

array([81, 52, 18, 71, 77,  8, 16, 42, 11,  8], dtype=int32)

In [33]:
data

array([81, 52, 18, 71, 77,  8, 16, 42, 11,  8], dtype=int32)

In [ ]:
np.median(data)

np.float64(30.0)

In [37]:
np.mean(data)

np.float64(38.4)

In [40]:
q1=np.percentile(data,25)
q1

np.float64(12.25)

In [42]:
q2 = np.percentile(data,50)
q2

np.float64(30.0)

In [43]:
q3 = np.percentile(data,75)

In [45]:
rang = q3-q1
rang

np.float64(54.0)